### PR TITLE
Added Xunit

### PR DESCRIPTION
**Pull request by gusen180**
Hope it's done correctly

### CODE REVIEW

**Comment by gusen180** [comment]
@matsskoglund Can you check my stuff :)

**Comment by matsskoglund** [comment]
Yup, I check

**Comment by matsskoglund** [comment]
@gusen180 I fixed a minor misspell and renamed the test class and updated a comment. I cloned, built, restored, executed the tests and run the application and it worked perfectly.

The global.json file that Visual Studio created when the project was created has the following entry ""projects": [ "src", "test" ]. I think that means that it expect the project(s) should to be in the "src" folder and the test project(s) in a "test" folder. What about creating a folder named "test" side-by-side of the "src" folder and move the "dotnetcoreapiTest" folder into that test folder?

**Comment by gusen180** [comment]
Hmm strange, have a test folder in my project. Something must have gone wrong. Checking it.
xunit

**Comment by matsskoglund** [comment]
Not meaning to be picky but since we are in the beginning we perhaps need to decide some details. Should the folder be "Test" or "test"? perhaps we should stick to one format, thus either "Src", "Test" or "src", "test"? 

Is it ok if I change the folder name to "test" since it will then follow the format in the global.json file and the src directory created by Visual Studio?

**Comment by gusen180** [comment]
It should be test and not Test. Been trying for an hour to get git to understand that. My git skills are failing me atm. 

Now both are checked in but only get one locally

**Comment by gusen180** [comment]
When I checkout the branch locally everything is correct. Everything is in a folder called "test". But here in GitHub the files in "test" locally are divided between "Test" and "test".

**Comment by matsskoglund** [comment]
Now it should be fixed

**Pull request merged**
